apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: portals-db
  namespace: portals
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: app
      owner: app
