environment: 
  APP_KEY: <INSERT_YOUR_SECURE_APP_KEY_HERE>
  APP_URL: https://portals.fsr5.de
  APP_DEBUG: "false"
  APP_ENV: production
  APP_FORCE_HTTPS: "true"
  APP_EVENT_TYPE: "demo"
  TUTOR_PASSWORD: password
  ADMIN_PASSWORD: admin
  DB_HOST: portals-db-rw.portals.svc
  DB_PASSWORD: <GET_PASSWORD_FROM_DB_SECRET>
  DB_USERNAME: portals
  DB_DATABASE: portals
  REDIS_HOST: portals-redis-leader.portals.svc
  REDIS_PORT: "6379"
  REDIS_PASSWORD: password
ingress:
  hosts:
    - portals.fsr5.de
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/limit-rps: "500"
replicaCount: 5
migrateJob:
  onInstall: true
  onUpgrade: false
  seed: true
  tutorsCsvConfigMapName: portals-tutors-csv
  studentsCsvConfigMapName: portals-students-csv
hpa:
  enabled: true
  minReplicas: 5
  maxReplicas: 10
  averageCPUUtilization: 90
