environment: 
  APP_KEY: <INSERT_YOUR_SECURE_APP_KEY_HERE>
  APP_URL: https://portals.fsr5.de
  APP_DEBUG: "false"
  TUTOR_PASSWORD: password
  ADMIN_PASSWORD: admin
  DB_HOST: portals-db-rw.portals.svc
  DB_PASSWORD: <GET_PASSWORD_FROM_DB_SECRET>
  DB_USERNAME: portals
  DB_DATABASE: portals
  REDIS_HOST: portals-redis-sentinel.portals.svc
  REDIS_PASSWORD: password
ingress:
  hosts:
    - portals.fsr5.de
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
replicaCount: 3
