apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: <CLUSTER_NAME>-md-0-fsn1
  namespace: <CLUSTER_NAME>
spec:
  clusterName: <CLUSTER_NAME>
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: <CLUSTER_NAME>-md-0
      clusterName: <CLUSTER_NAME>
      failureDomain: fsn1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: <CLUSTER_NAME>-md-0
      version: <KUBERNETES_VERSION>
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: <CLUSTER_NAME>-md-0-nbg1
  namespace: <CLUSTER_NAME>
spec:
  clusterName: <CLUSTER_NAME>
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: <CLUSTER_NAME>-md-0
      clusterName: <CLUSTER_NAME>
      failureDomain: nbg1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: <CLUSTER_NAME>-md-0
      version: <KUBERNETES_VERSION>
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: <CLUSTER_NAME>-md-0-hel1
  namespace: <CLUSTER_NAME>
spec:
  clusterName: <CLUSTER_NAME>
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: <CLUSTER_NAME>-md-0
      clusterName: <CLUSTER_NAME>
      failureDomain: hel1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: <CLUSTER_NAME>-md-0
      version: <KUBERNETES_VERSION>
