env:
  HCLOUD_TOKEN:
    valueFrom:
      secretKeyRef:
        name: ccm
        key: token
  NODE_NAME:
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

# wait for new hcloud ccm release before uncommenting
#replicaCount: 3
args:
  leader-elect: "true"

networking:
  enabled: true
  clusterCIDR: 10.10.0.0/16
  network:
    valueFrom:
      secretKeyRef:
        name: ccm
        key: network
