rollOutCiliumPods: true
priorityClassName: "system-node-critical"

hubble:
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
ipam:
  mode: "kubernetes"

kubeProxyReplacement: strict
k8sServiceHost: <CLUSTER_API_URL>
k8sServicePort: 6443

hostServices:
  enabled: false

externalIPs:
  enabled: true

nodePort:
  enabled: true

hostPort:
  enabled: true

image:
  pullPolicy: IfNotPresent

operator:
  rollOutPods: true
  priorityClassName: "system-node-critical"
  prometheus:
    enabled: true

prometheus:
  enabled: true
