name: Docker CI (release)

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build -f ./Dockerfile . --tag ${{ env.REGISTRY }}/portals:${{ env.RELEASE_VERSION }} --tag ${{ env.REGISTRY }}/portals:latest --build-arg
          docker push ${{ env.REGISTRY }}/portals:${{ env.RELEASE_VERSION }}
          docker push ${{ env.REGISTRY }}/portals:latest